### ISSUE TITLE
Custom TERRAKUBE ADMIN group

### ISSUE THREAD

**Issue by Eric-Llistar** [AzBuilder/docs#14]
Unable to change and validate TERRAKUBE_ADMIN group name
I've edited every entry related with TERRAKUBE_ADMIN and also configured ldif files but i'm unable to create an organization

Unable to find logs related with the organization creation.
Is there any other documentation related with that? I've been checking dex connector but seems that there's something missing

**Comment by alfespa17** [comment]
Hello @Eric-Llistar if you are using the helm chart you just need to overwrite the group name like this:

```
## Terrakube Security
security:
  adminGroup: "<<CHANGE_THIS>>" 
```

That will overwrite the value here 

https://github.com/AzBuilder/terrakube-helm-chart/blob/efd3585024cd7236cabfd389ed090d3d2add721f/charts/terrakube/templates/secrets-api.yaml#L19

The container is using this environment variable to get the admin group name

`TERRAKUBE_ADMIN_GROUP`

I hope this can help

**Comment by Eric-Llistar** [comment]
Sorry! I've deployed via docker compose

**Comment by alfespa17** [comment]
> Sorry! I've deployed via docker compose

It will be the same just update that environment variable

https://github.com/AzBuilder/terrakube/blob/9ef544546474031188c955d1bc68b6d98a93f97f/api/src/main/resources/application.properties#L58

**Comment by Eric-Llistar** [comment]
Hi Alfredo!
First of all thanks for your quick answers.
Unfortunately still not working.. I've just edited this variable twice:
org.terrakube.owner=${TERRAKUBE_ADMIN_GROUP:MY_GROUP_NAME}
org.terrakube.owner=$"MY_GROUP_NAME"

But didn't work

I've also modified the config-ldap.ldif on ##group definition##  section

dn: cn=MY_GROUP_NAME,ou=XXX,ou=XXX,dc=XXX,dc=XXX
objectClass: groupOfNames
cn: MY_GROUP_NAME
member: cn=username,ou=MY_GROUP_NAME,ou=XXX,ou=XXX,dc=XXX,dc=XXX


Is that configuration correct?
Thanks!

**Comment by alfespa17** [comment]
you need to make sure to update the org name

```
    dn: {{ .Values.openldap.baseRoot }}
    dc: example
    objectClass: dcObject
    objectClass: organization
    o: Example, Inc
```

The user here

```
    dn: cn={{ .Values.openldap.adminUser }},ou=users,{{ .Values.openldap.baseRoot }}
    objectClass: inetOrgPerson
    sn: Admin
    cn: Admin
    mail: admin@example.com
    userpassword: {{ .Values.openldap.adminPass }}
```

This part also
```
    dn: cn=TERRAKUBE_ADMIN,ou=Groups,{{ .Values.openldap.baseRoot }}
    objectClass: groupOfNames
    cn: TERRAKUBE_ADMIN
    member: cn={{ .Values.openldap.adminUser }},ou=users,{{ .Values.openldap.baseRoot }}
```

And you also need to change this environment variables for the openldap container

https://github.com/AzBuilder/terrakube/blob/90a5eb260293ea1c734b3534a70e882003df9712/docker-compose/docker-compose.yaml#L38

I hope that can help you

**Comment by Eric-Llistar** [comment]
Sure. Still the same. Let me share with you which files I've modified in order to try to find what is the problem:


- terrakube/api/src/main/resources/application.properties:
```
################
#OWNER INSTANCE#
################
org.terrakube.owner=${TERRAKUBE_ADMIN_GROUP:**MY_ADMIN GROUP_NAME**}
```


- terrakube/docker-compose/api.env
`TERRAKUBE_ADMIN_GROUP=**"MY_ADMIN GROUP_NAME"**`


- terrakube/docker-compose/config-ldap.ldif
```
dn: dc=**my_company,dc=com**
dc: **my_company**
objectClass: dcObject
objectClass: organization
ou: **my_company**

dn: ou=**users_group,dc=my_company,dc=com**
ou: **users**
objectClass: organizationalunit

dn: cn=**admin_user,ou=users_group,dc=my_company,dc=com**
objectClass: inetOrgPerson
sn: 
cn: **admin_user**
mail: **email**
userpassword: **admin_password**

# Group definitions.

dn: ou=**users_group,ou=users,dc=my_company,dc=com**
objectClass: organizationalUnit
ou:**users_group**

# TERRAKUBE_ADMIN
dn: cn=**MY_ADMIN GROUP_NAME,ou=users_group,ou=users,dc=my_company,dc=com**
objectClass: groupOfNames
cn: **MY_ADMIN GROUP_NAME**
member: cn=**admin_user,ou=users_group,dc=my_company,dc=com**
```


- terrakube/docker-compose/config-ldap.yaml
```
connectors:
- type: ldap
  name: OpenLDAP
  id: ldap
  config:
    # The following configurations seem to work with OpenLDAP:
    #
    # 1) Plain LDAP, without TLS:
    host: **MY_HOSTNAME**:389


    # This would normally be a read-only user.
    bindDN: cn=**admin_user,ou=users_group,dc=my_company,dc=com**
    bindPW: **admin_password**

    usernamePrompt: Email Address

    userSearch:
      baseDN: **ou=users_group,ou=users,dc=my_company,dc=com**
      filter: "(objectClass=person)"
      username: userPrincipalName
      # "DN" (case sensitive) is a special attribute name. It indicates that
      # this value should be taken from the entity's DN not an attribute on
      # the entity.
      idAttr: DN
      emailAttr: userPrincipalName
      nameAttr: cn
```

 

- terrakube/docker-compose/docker-compose.yaml
```
ldap-service:
    image: bitnami/openldap:2.6.4-debian-11-r4
    environment:
      LDAP_TLS_VERIFY_CLIENT: try
      LDAP_ADMIN_USERNAME: "**admin_user**"
      LDAP_ADMIN_PASSWORD: "**admin_password**"
      LDAP_ROOT: "**dc=my_company,dc=com**"
      LDAP_CUSTOM_LDIF_DIR: "/ldifs"

```



ldap.yaml seems to be ok since I'm able to log in with domain credentials, but at the time to create an organization, I receive a "without permissions" message to create it

Is there any other file or section that should I fill?
Thanks!!

PD: Asterisks used to be to mark text as Bold but not working very well
